# test/test_em_dashes.py
"""One gate: no tracked file may contain an em dash.

AGENTS.md has banned them since the writing-style rules were written, and the
ban was enforced by nothing. The rule reads as being about prose, so the
strings shipped under `src/dbml_sharepoint/solutions/` were not treated as
covered by it, and they are the ones that reach a live site.

Nothing in the build can see one. An em dash in a list description saves,
reads back byte-identical, passes every deploy phase, and renders on an
operator's screen looking like the tool wrote it that way.

MEASURED 2026-08-16: the sweep this gate accompanies removed 60 of them from
20 files across 8 solution families, and 60 was the repository-wide total, so
none remain anywhere tracked. The gate is what holds that at zero.

The en dash is not banned and is not scanned for. The 22 that survive are all
numeric ranges in companion documents, which is what an en dash is for.
"""

import subprocess
from pathlib import Path

import pytest
from _paths import REPO_ROOT

#: An escape rather than the character, so this file is scanned like any
#: other rather than needing an exemption from itself.
EM_DASH = "\u2014"

#: Suffixes carrying text a human wrote or a human reads. A binary file has
#: no em dashes to find and decoding one wastes the run.
SCANNED = ("*.py", "*.md", "*.yaml", "*.yml", "*.dbml", "*.j2", "*.txt", "*.json")

#: Excluded for a reason, not for convenience:
#: - CHANGELOG.md is release history, correct as written and regenerated by
#:   release-please from commit subjects this gate already covers.
#: - superpowers/ holds specs and plans, which are point-in-time records.
EXCLUDED = (
    "CHANGELOG.md",
    "docs/superpowers/",
)


def _tracked_text() -> list[Path]:
    """Every tracked file an em dash could hide in."""
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", *SCANNED],
        cwd=REPO_ROOT, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        # Skipping is honest; returning [] would make this vacuously pass and
        # it would stay green forever without reading a single file.
        pytest.skip(f"git ls-files unavailable: {result.stderr.strip()!r}")
    return [
        REPO_ROOT / name
        for name in result.stdout.split("\0")
        if name and not name.startswith(EXCLUDED)
    ]


def _offenders_in(path: Path, relative: str) -> list[str]:
    """Every line of `path` carrying an em dash, named for the failure report.

    Separate from the gate so the proof below runs this scan rather than a
    copy of it. A proof that reimplements what it is proving passes when the
    real scan is broken.
    """
    return [
        f"{relative}:{number}: {line.strip()[:80]!r}"
        for number, line in enumerate(
            path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1,
        )
        if EM_DASH in line
    ]


def test_no_tracked_file_contains_an_em_dash() -> None:
    """The failure names every site, so the fix is a list rather than a hunt."""
    scanned = _tracked_text()
    # Without this the gate passes on an empty list, which is how a path
    # filter that stops matching goes unnoticed.
    assert len(scanned) > 100, f"only {len(scanned)} files scanned, so this pins nothing"

    offenders = [
        offender
        for path in scanned
        for offender in _offenders_in(path, path.relative_to(REPO_ROOT).as_posix())
    ]

    assert not offenders, (
        "Tracked files contain an em dash, which AGENTS.md bans. Use a comma, "
        "parentheses, or a new sentence. A dash inside a shipped solution "
        "string reaches an operator's screen:\n" + "\n".join(offenders)
    )


def test_the_gate_would_catch_a_reintroduced_em_dash(tmp_path: Path) -> None:
    """Proof the scan bites, independent of the repository being clean.

    The gate above passes today by finding nothing, which is the same
    observable result as a scan that reads no files or matches no character.
    """
    seeded = tmp_path / "release.yaml"
    seeded.write_text(
        "title: Risk register\n"
        f"description: Owner view {EM_DASH} refreshed nightly\n",
        encoding="utf-8", newline="\n",
    )

    expected = f"release.yaml:2: 'description: Owner view {EM_DASH} refreshed nightly'"
    assert _offenders_in(seeded, "release.yaml") == [expected]
