# test/test_text_encoding.py
"""Two gates over the characters this project writes.

AGENTS.md has banned em dashes since the writing-style rules were written,
and nothing enforced it. The rule reads as being about prose, so the strings
shipped under `src/dbml_sharepoint/solutions/` were not treated as covered by
it, and those strings reach a live site.

Nothing in the build can see one. An em dash in a list description saves,
reads back byte-identical, passes every deploy phase, and renders on an
operator's screen looking like the tool wrote it that way. The same is true of
every other non-ASCII character, which is why the second gate covers every
codepoint in the shipped surface.

Each gate records its own sweep. MEASURED 2026-08-16: the em-dash sweep
removed 60 from 20 files across 8 solution families, which was the
repository-wide total; the ASCII sweep removed 537 from 128 shipped files,
which was the whole of what the wheel carried. Both gates now fail on the
first reintroduction.

The en dash is not banned and is not scanned for. MEASURED 2026-08-16, after
the ASCII sweep: 7 remain across 663 tracked files, all under `website/`,
which the wheel does not ship. Five are numeric ranges and the other two are
both in one workflow name.
"""

import subprocess
import tomllib
import unicodedata
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest
from _paths import REPO_ROOT

#: Written as an escape so this file stays ASCII and its own gates scan it
#: like any other file, with no exemption.
EM_DASH = "\u2014"

#: Suffixes carrying text a human wrote or a human reads. A binary file has
#: no em dashes to find and decoding one wastes the run.
SCANNED = ("*.py", "*.md", "*.yaml", "*.yml", "*.dbml", "*.j2", "*.txt", "*.json")

#: Excluded because:
#: - CHANGELOG.md is release history, correct as written and regenerated by
#:   release-please from commit subjects this gate already covers.
#: - superpowers/ holds specs and plans, which are point-in-time records.
EXCLUDED = (
    "CHANGELOG.md",
    "docs/superpowers/",
)

#: Where hatchling records what reaches the wheel. Named once so a failure can
#: say which key moved.
WHEEL_PACKAGES = "tool.hatch.build.targets.wheel.packages"


def _tracked_text() -> list[Path]:
    """Every tracked file an em dash could hide in."""
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", *SCANNED],
        cwd=REPO_ROOT, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        # Skipping is honest; returning [] would make this vacuously pass and
        # it would stay green forever without reading a single file.
        pytest.skip(f"git ls-files unavailable: {result.stderr.strip()!r}")
    return [
        REPO_ROOT / name
        for name in result.stdout.split("\0")
        if name and not name.startswith(EXCLUDED)
    ]


def _relative(path: Path) -> str:
    """The roots are written this way, so a scanned path is matched this way."""
    return path.relative_to(REPO_ROOT).as_posix()


def _roots_in(config: dict[str, Any]) -> tuple[str, ...]:
    """The wheel's source paths named by a parsed pyproject.

    Split from the file read so the proof below can feed it an invented config.
    """
    node: object = config
    for key in WHEEL_PACKAGES.split("."):
        if not isinstance(node, dict) or key not in node:
            pytest.fail(
                f"pyproject.toml has no {WHEEL_PACKAGES}, so this gate cannot "
                "tell what the wheel ships. Point it at the new key rather "
                "than hard-coding a path."
            )
        node = node[key]
    project = config.get("project")
    readme = project.get("readme") if isinstance(project, dict) else None
    if not isinstance(node, list) or not all(isinstance(p, str) for p in node):
        pytest.fail(f"{WHEEL_PACKAGES} is {node!r}, expected a list of paths")
    if not isinstance(readme, str):
        pytest.fail(f"project.readme is {readme!r}, expected a path")
    return (*node, readme)


def _shipped_roots() -> tuple[str, ...]:
    """Packaging names what the wheel is built from; this reads it back."""
    text = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    return _roots_in(tomllib.loads(text))


def _shipped_files(roots: tuple[str, ...]) -> list[Path]:
    """Every tracked file under a shipped root, whatever its extension.

    `SCANNED` lists the suffixes the em-dash gate reads. Reusing it here would
    silently drop whatever extension ships next.
    """
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", *roots],
        cwd=REPO_ROOT, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        pytest.skip(f"git ls-files unavailable: {result.stderr.strip()!r}")
    return [REPO_ROOT / name for name in result.stdout.split("\0") if name]


def _offending_lines(
    path: Path, relative: str, offends: Callable[[str], str],
) -> list[str]:
    """Lines where `offends` returns a label, formatted for the failure report.

    One helper so each proof below runs the scan the gate runs. A proof that
    reimplements it passes while the real scan is broken.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        # Decoding with errors="replace" turned a cp1252 em dash into U+FFFD,
        # which the em-dash gate then did not recognise and reported clean.
        return [f"{relative}: not UTF-8, {exc.reason} at byte {exc.start}"]
    return [
        f"{relative}:{number}: {label}: {line.strip()[:80]!r}"
        for number, line in enumerate(text.splitlines(), start=1)
        if (label := offends(line))
    ]


def _em_dash(line: str) -> str:
    """The report prints this label, so it is returned instead of a bool."""
    return "em dash" if EM_DASH in line else ""


def _non_ascii(line: str) -> str:
    """Names every offending codepoint, so a reader knows what to replace."""
    found = sorted({c for c in line if not c.isascii()})
    return ", ".join(f"U+{ord(c):04X} {unicodedata.name(c, 'unnamed')}" for c in found)


def test_no_tracked_file_contains_an_em_dash() -> None:
    """The failure names every offending file and line."""
    scanned = _tracked_text()
    # Without this the gate passes on an empty list, which is how a path
    # filter that stops matching goes unnoticed.
    assert len(scanned) > 100, f"only {len(scanned)} files scanned, so this pins nothing"

    offenders = [
        offender
        for path in scanned
        for offender in _offending_lines(path, _relative(path), _em_dash)
    ]

    assert not offenders, (
        "Tracked files contain an em dash, which AGENTS.md bans. Use a comma, "
        "parentheses, or a new sentence. A dash inside a shipped solution "
        "string reaches an operator's screen:\n" + "\n".join(offenders)
    )


def test_the_gate_would_catch_a_reintroduced_em_dash(tmp_path: Path) -> None:
    """Proof the scan reports a seeded em dash, independent of a clean tree.

    The gate above passes today by finding nothing, which is the same
    observable result as a scan that reads no files or matches no character.
    """
    seeded = tmp_path / "release.yaml"
    seeded.write_text(
        "title: Risk register\n"
        f"description: Owner view {EM_DASH} refreshed nightly\n",
        encoding="utf-8", newline="\n",
    )

    expected = (
        f"release.yaml:2: em dash: "
        f"'description: Owner view {EM_DASH} refreshed nightly'"
    )
    assert _offending_lines(seeded, "release.yaml", _em_dash) == [expected]


def test_shipped_text_is_ascii() -> None:
    """Every character the wheel ships is ASCII.

    `U+2192` fails to encode on cp1252, cp850 and cp437 alike, so no single
    code page is the constraint. Packaging decides what ships, so no
    contributor has to judge the boundary file by file.
    """
    shipped = _shipped_files(_shipped_roots())
    assert len(shipped) > 100, (
        f"only {len(shipped)} shipped files scanned, so this pins nothing"
    )

    offenders = [
        line
        for path in shipped
        for line in _offending_lines(path, _relative(path), _non_ascii)
    ]
    assert not offenders, (
        "Shipped text contains non-ASCII characters. Replace each with its "
        "ASCII spelling; `catalogue._TERMINAL_SPELLINGS` is the table:\n"
        + "\n".join(offenders)
    )


def test_the_shipped_roots_come_from_packaging() -> None:
    """The gate's file set is derived from pyproject, not copied from it.

    Asserted against an invented config, because asserting the real values
    passes just as well against a hard-coded pair.
    """
    invented = _roots_in({
        "project": {"readme": "DESCRIPTION.rst"},
        "tool": {"hatch": {"build": {"targets": {"wheel": {
            "packages": ["src/one", "src/two"],
        }}}}},
    })
    assert invented == ("src/one", "src/two", "DESCRIPTION.rst")
    # And what the real file says today, so moving either key fails here
    # instead of silently narrowing what the gate scans.
    assert _shipped_roots() == ("src/dbml_sharepoint", "README.md")


def test_the_scan_reports_a_seeded_non_ascii_character(tmp_path: Path) -> None:
    """A seeded arrow must be reported, whatever the real tree contains."""
    seeded = tmp_path / "guide.md"
    seeded.write_text(
        "clean line\nDraft \u2192 Active\n", encoding="utf-8", newline="\n",
    )

    found = _offending_lines(seeded, "guide.md", _non_ascii)
    assert found == [
        "guide.md:2: U+2192 RIGHTWARDS ARROW: 'Draft \u2192 Active'",
    ]


def test_the_report_names_a_path_from_the_repository_root() -> None:
    """No gate above can pin this, because it only runs inside a failure message.

    Replacing `_relative` with `path.name` leaves every test above green and
    turns the failure report into an ambiguous list of basenames.
    """
    assert _relative(REPO_ROOT / "src" / "dbml_sharepoint" / "cli.py") == (
        "src/dbml_sharepoint/cli.py"
    )
