// tools/dbml-sharepoint/website/docusaurus.config.js
// Docs-only Docusaurus site for dbml-sharepoint. The docs ARE the site
// (routeBasePath '/'); no blog, no landing page. API pages under
// docs/api/ are generated by scripts/generate_api.py. Regenerate after
// changing the Python or template sources.

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'dbml-sharepoint',
  tagline:
    'DBML + YAML in, fail-closed browser-console SharePoint deployment out',
  url: 'https://firmfooting.github.io',
  baseUrl: '/dbml-sharepoint/',
  organizationName: 'firmfooting',
  projectName: 'dbml-sharepoint',
  onBrokenLinks: 'throw',
  favicon: 'img/favicon.ico',

  // .md renders as CommonMark, .mdx as MDX. Generated pages reproduce
  // docstrings and template comments verbatim; CommonMark keeps their
  // braces and angle brackets from being parsed as JSX.
  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.js',
        },
        blog: false,
        pages: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: 'dbml-sharepoint',
        logo: {
          alt: 'firmfooting',
          src: 'img/icon.svg',
        },
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docs',
            position: 'left',
            label: 'Documentation',
          },
          {
            href: 'https://github.com/firmfooting/dbml-sharepoint',
            position: 'right',
            label: 'GitHub',
          },
        ],
      },
      // Footer `to` paths resolve against baseUrl, and onBrokenLinks
      // checks them at build time. `href` targets are external and are not.
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              { label: 'Getting started', to: '/getting-started' },
              { label: 'Concepts', to: '/concepts/architecture' },
              { label: 'Reference', to: '/reference/mapping' },
            ],
          },
          {
            title: 'Project',
            items: [
              {
                label: 'GitHub',
                href: 'https://github.com/firmfooting/dbml-sharepoint',
              },
              {
                label: 'Changelog',
                href: 'https://github.com/firmfooting/dbml-sharepoint/blob/main/CHANGELOG.md',
              },
              {
                label: 'Security',
                href: 'https://github.com/firmfooting/dbml-sharepoint/blob/main/SECURITY.md',
              },
            ],
          },
          {
            title: 'firmfooting',
            items: [
              { label: 'Org on GitHub', href: 'https://github.com/firmfooting' },
              { label: 'formwork', href: 'https://github.com/firmfooting/formwork' },
              { label: 'vsdxkit', href: 'https://github.com/firmfooting/vsdxkit' },
              { label: 'branding', href: 'https://github.com/firmfooting/branding' },
            ],
          },
        ],
        copyright:
          'dbml-sharepoint, MIT licensed. Part of firmfooting. ' +
          'Not affiliated with or endorsed by Microsoft.',
      },
      prism: {
        additionalLanguages: ['json', 'yaml', 'sql', 'bash'],
      },
    }),
};

export default config;
