// tools/dbml-sharepoint/website/docusaurus.config.js
// Docs-only Docusaurus site for dbml-sharepoint. The docs ARE the site
// (routeBasePath '/'); no blog, no landing page. API pages under
// docs/api/ are generated by scripts/generate_api.py. Regenerate after
// changing the Python or template sources.

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'dbml-sharepoint',
  tagline:
    'DBML + YAML in, fail-closed browser-console SharePoint deployment out',
  url: 'https://shauneccles.github.io',
  baseUrl: '/dbml-sharepoint/',
  organizationName: 'shauneccles',
  projectName: 'dbml-sharepoint',
  onBrokenLinks: 'throw',

  // .md renders as CommonMark, .mdx as MDX. Generated pages reproduce
  // docstrings and template comments verbatim; CommonMark keeps their
  // braces and angle brackets from being parsed as JSX.
  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.js',
        },
        blog: false,
        pages: false,
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: 'dbml-sharepoint',
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docs',
            position: 'left',
            label: 'Documentation',
          },
        ],
      },
      footer: {
        style: 'dark',
        copyright: 'dbml-sharepoint, MIT licensed.',
      },
      prism: {
        additionalLanguages: ['json', 'yaml', 'sql', 'bash'],
      },
    }),
};

export default config;
