// tools/dbml-sharepoint/website/sidebars.js
// One autogenerated sidebar: structure comes from the docs/ tree,
// ordering from each page's sidebar_position and each folder's
// _category_.json. Generated API pages slot in like any other doc.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
