# src/dbml_sharepoint/generators/report_sql.py
"""The T-SQL side of the reporting pack.

A single SQLCMD script of ``CREATE OR ALTER VIEW`` statements: a typed view
per list plus an ``_Enriched`` view joining each lookup to its display
column, for lists landed in a warehouse by any extract process, and the
dictionary, model-info and drift-audit views built from embedded VALUES
rows.

Everything here returns SQL text, and every string that reaches it goes
through :func:`_sql_string`. What the views CARRY is decided by
``analysis/reporting/plan.py``; this module only writes it down. Person
columns land differently per extract tool, so the views carry them as
display-name text, and no derived column reaches this side because a
row-level M expression has no SQL to translate to.
"""

from dbml_sharepoint.analysis.report_columns import projection_output_name
from dbml_sharepoint.analysis.reporting.dictionary import (
    dictionary_rows,
    metadata_rows,
)
from dbml_sharepoint.analysis.reporting.plan import (
    ListPlan,
    build_plans,
    tables_for_role,
)
from dbml_sharepoint.bundle import REPORT_GUIDE
from dbml_sharepoint.model.mapping_types import MappingBundle
from dbml_sharepoint.model.parser import Schema
from dbml_sharepoint.model.release import Release

_SQL_SITE_URL_PLACEHOLDER = "https://yourtenant.sharepoint.com/sites/YourSite"


def _sql_header(site_url: str | None) -> str:
    """The SQLCMD preamble, with SiteUrl set to the real site when known.

    Same rule as the M queries: ``build`` was given ``--site-url`` and bakes
    it in, ``report`` was not and leaves the placeholder to be edited. The
    trailing slash is dropped because ItemURL concatenates a path that
    already starts with one. ``$(SiteUrl)`` is a raw prefix here, with no
    normalisation step of the kind the M queries have to absorb it later.
    """
    setvar = (
        _SQL_SITE_URL_PLACEHOLDER if site_url is None else site_url.rstrip("/")
    )
    aim = (
        """\
-- Run in SQLCMD mode; point the variables at your landing/reporting schemas
-- and SiteUrl at the site the lists were deployed to (no trailing slash).
-- It feeds the ItemURL helper column linking each row back to SharePoint."""
        if site_url is None else
        """\
-- Run in SQLCMD mode; point the variables at your landing/reporting schemas.
-- SiteUrl is already set to the site this bundle was built for. It feeds
-- the ItemURL helper column linking each row back to SharePoint."""
    )
    return f"""\
-- Generated by dbml-sharepoint; regenerate rather than hand-edit.
-- T-SQL views over SharePoint list data landed in a warehouse.
{aim}
-- Assumes each list lands as a table named after the list, with columns
-- named after the SharePoint internal column names (see {REPORT_GUIDE}).
:setvar LandingSchema landing
:setvar ReportSchema rpt
:setvar SiteUrl {setvar}
GO
"""


def _render_sql_view(plan: ListPlan) -> str:
    col_lines = [
        f"    CAST(t.[{name}] AS {sql_type}) AS [{name}]"
        for name, sql_type in plan.sql_columns
    ]
    col_lines.append(
        f"    CONCAT('$(SiteUrl){plan.item_url_path}', CAST(t.[Id] AS INT)) "
        "AS [ItemURL]",
    )
    cols = ",\n".join(col_lines)
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[vw_{plan.list_title}] AS\n"
        f"SELECT\n{cols}\n"
        f"FROM [$(LandingSchema)].[{plan.list_title}] AS t;\n"
        "GO\n"
    )


def _render_sql_enriched(plan: ListPlan) -> str:
    select_lines = ["    t.*"]
    join_lines = []
    for i, (fk_col, target_title, display, projections) in enumerate(
        plan.joins, start=1,
    ):
        alias = f"j{i}"
        base = fk_col.removesuffix("Id")
        select_lines.append(f"    {alias}.[{display}] AS [{base}{display}]")
        # The dependent lookups this column projects, off the SAME join the
        # display column already uses. Selected from the target's view rather
        # than from this list's landed table, because no extract is required
        # to have carried a read-only field across and the target's own view
        # has the column either way. `build_plans` has already dropped any
        # the target does not carry.
        select_lines += [
            f"    {alias}.[{target_column}] AS "
            f"[{projection_output_name(base, target_column)}]"
            for target_column in projections
        ]
        join_lines.append(
            f"LEFT JOIN [$(ReportSchema)].[vw_{target_title}] AS {alias}\n"
            f"    ON t.[{fk_col}] = {alias}.[Id]",
        )
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[vw_{plan.list_title}_Enriched] AS\n"
        "SELECT\n" + ",\n".join(select_lines) + "\n"
        f"FROM [$(ReportSchema)].[vw_{plan.list_title}] AS t\n"
        + "\n".join(join_lines) + ";\n"
        "GO\n"
    )


def generate_sql_views(
    schema: Schema, bundle: MappingBundle, site_role: str,
    *,
    site_url: str | None = None,
) -> str:
    """A single SQLCMD script: typed view per list + _Enriched join views.

    ``site_url``, when known, is written into the ``:setvar SiteUrl`` line
    so the script needs no editing; otherwise a placeholder is left there.
    """
    plans = build_plans(schema, bundle, site_role)
    parts = [_sql_header(site_url)]
    parts += [_render_sql_view(plan) for plan in plans]
    parts += [_render_sql_enriched(plan) for plan in plans if plan.joins]
    return "\n".join(parts)


def _sql_string(text: str) -> str:
    """An N'...' T-SQL literal: single quotes are escaped by doubling."""
    return "N'" + text.replace("'", "''") + "'"


def _render_sql_values_view(
    view_name: str, columns: list[str], row_literals: list[str],
) -> str:
    col_list = ", ".join(f"[{c}]" for c in columns)
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[{view_name}] AS\n"
        f"SELECT {col_list}\n"
        "FROM (VALUES\n"
        + ",\n".join(f"    ({row})" for row in row_literals)
        + f"\n) AS v({col_list});\n"
        "GO\n"
    )


def _render_user_added_columns_sql(plans: list[ListPlan], prefix: str) -> str:
    """Drift-audit view over the landing schema: columns present on the
    landed tables that the schema does not declare. Sees only what the
    extract process lands (the M audit query is the live control);
    extractor-added audit columns (e.g. LoadDate) surface as recognisable
    rows."""
    if not plans:
        return ""
    table_list = ", ".join(_sql_string(plan.list_title) for plan in plans)
    expected_rows = []
    for plan in plans:
        names = ["Id"] + [name for name, _ in plan.sql_columns]
        for name in dict.fromkeys(names):
            expected_rows.append(
                f"    ({_sql_string(plan.list_title)}, {_sql_string(name)})",
            )
    # Emitting SQL text is this generator's purpose; identifiers come
    # from the validated schema, never from runtime user input.
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[vw_{prefix}UserAddedColumns] AS\n"  # noqa: S608
        "-- Drift audit: landed columns the schema does not declare. Expected\n"
        "-- EMPTY. Only sees columns the extract process lands.\n"
        "SELECT c.TABLE_NAME AS [List], c.COLUMN_NAME AS [Column],\n"
        "       c.DATA_TYPE AS [LandedType]\n"
        "FROM INFORMATION_SCHEMA.COLUMNS AS c\n"
        "WHERE c.TABLE_SCHEMA = '$(LandingSchema)'\n"
        f"  AND c.TABLE_NAME IN ({table_list})\n"
        "  AND NOT EXISTS (SELECT 1 FROM (VALUES\n"
        + ",\n".join(expected_rows)
        + "\n  ) AS d([List], [Column])\n"
        "  WHERE d.[List] = c.TABLE_NAME AND d.[Column] = c.COLUMN_NAME);\n"
        "GO\n"
    )


def generate_dictionary_sql(
    schema: Schema,
    bundle: MappingBundle,
    site_role: str,
    *,
    release: Release | None = None,
    generated_at: str = "",
    source_schema: str = "",
    source_mapping: str = "",
) -> str:
    """The data dictionary as SQL views built from embedded VALUES rows (no
    landing table needed), so warehouse-driven reports can surface the same
    dictionary page."""
    prefix = bundle.mapping.prefix
    dd_rows = [
        ", ".join([str(i)] + [_sql_string(cell) for cell in row])
        for i, row in enumerate(dictionary_rows(schema, bundle, site_role), start=1)
    ]
    tables = tables_for_role(schema, bundle, site_role)
    mi_rows = [
        _sql_string(field_name) + ", " + _sql_string(value)
        for field_name, value in metadata_rows(
            bundle, site_role, len(tables),
            release, generated_at, source_schema, source_mapping,
        )
    ]
    audit_view = _render_user_added_columns_sql(
        build_plans(schema, bundle, site_role), prefix,
    )
    return (
        _render_sql_values_view(
            f"vw_{prefix}DataDictionary",
            ["SortOrder", "List", "Column", "Type",
             "Required", "Unique", "Default", "Retired", "SupersededBy",
             "PopulatedWhen", "SaveRule", "Description"],
            dd_rows,
        )
        + "\n"
        + _render_sql_values_view(
            f"vw_{prefix}ModelInfo", ["Field", "Value"], mi_rows,
        )
        + ("\n" + audit_view if audit_view else "")
    )
