# src/dbml_sharepoint/generators/reportgen.py
"""Report-query generator: Power Query (M) and T-SQL views from the schema.

The same DBML + mapping that provisions the lists also describes how to
report on them. This module emits:

- one Power Query (M) query per list, ``OData.Feed`` against the list's
  REST endpoint, with lookup and person columns expanded to a join key plus
  display column, and column types applied from the deployer's own typemap.
  ``build`` knows the site (``--site-url``) and bakes it into every query,
  so a shipped bundle has nothing to configure; the standalone ``report``
  command knows no site and falls back to a ``SiteUrl`` text parameter;
- a single T-SQL script of ``CREATE OR ALTER VIEW`` statements (SQLCMD
  variables for the landing/report schemas): a typed view per list plus an
  ``_Enriched`` view joining each lookup to its display column, for lists
  landed in a warehouse by any extract process;
- guide.md with usage instructions and the Power BI relationship table
  derived from the DBML refs.

Cross-site reference columns are extension-expanded at deploy time into
shapes the core cannot know; they are skipped here and listed in
guide.md. Person columns land differently per extract tool, so the SQL
views carry them as display-name text while the M queries expand both the
site-user id and display name.
"""

from pathlib import Path
from typing import Any

from dbml_sharepoint.analysis.exports import MULTI_VALUE_JOIN
from dbml_sharepoint.analysis.lookups import lookup_display_columns
from dbml_sharepoint.analysis.report_columns import (
    DATE_ZONE_RESOLVED_COLUMN,
    ITEM_URL_RESOLVED_COLUMN,
    REPORT_KEY_SUFFIX,
    USERS_KEY_LIST,
    fk_key_column,
    person_key_column,
    projection_output_name,
)
from dbml_sharepoint.analysis.reporting.dictionary import (
    column_rows_for_table,
    dictionary_rows,
    metadata_rows,
    users_dictionary_rows,
)
from dbml_sharepoint.analysis.reporting.plan import (
    ListPlan,
    build_plans,
    tables_for_role,
)
from dbml_sharepoint.analysis.timezones import (
    WINDOW_END,
    WINDOW_START,
    zone_table,
)
from dbml_sharepoint.analysis.typemap import CALCULATED_TYPES
from dbml_sharepoint.bundle import (
    REPORT_DICTIONARY,
    REPORT_DIR,
    REPORT_GUIDE,
    REPORT_VIEWS_SQL,
    write_artifact,
)
from dbml_sharepoint.generators._indexes import deployable_index_columns
from dbml_sharepoint.generators.report_m import (
    generate_dictionary_powerquery,
    generate_powerquery,
)
from dbml_sharepoint.model.mapping_types import MappingBundle
from dbml_sharepoint.model.parser import Schema
from dbml_sharepoint.model.release import Release

# ------------------------------------------------------------------ SQL views


_SQL_SITE_URL_PLACEHOLDER = "https://yourtenant.sharepoint.com/sites/YourSite"


def _sql_header(site_url: str | None) -> str:
    """The SQLCMD preamble, with SiteUrl set to the real site when known.

    Same rule as the M queries: ``build`` was given ``--site-url`` and bakes
    it in, ``report`` was not and leaves the placeholder to be edited. The
    trailing slash is dropped because ItemURL concatenates a path that
    already starts with one. ``$(SiteUrl)`` is a raw prefix here, with no
    normalisation step of the kind the M queries have to absorb it later.
    """
    setvar = (
        _SQL_SITE_URL_PLACEHOLDER if site_url is None else site_url.rstrip("/")
    )
    aim = (
        """\
-- Run in SQLCMD mode; point the variables at your landing/reporting schemas
-- and SiteUrl at the site the lists were deployed to (no trailing slash).
-- It feeds the ItemURL helper column linking each row back to SharePoint."""
        if site_url is None else
        """\
-- Run in SQLCMD mode; point the variables at your landing/reporting schemas.
-- SiteUrl is already set to the site this bundle was built for. It feeds
-- the ItemURL helper column linking each row back to SharePoint."""
    )
    return f"""\
-- Generated by dbml-sharepoint; regenerate rather than hand-edit.
-- T-SQL views over SharePoint list data landed in a warehouse.
{aim}
-- Assumes each list lands as a table named after the list, with columns
-- named after the SharePoint internal column names (see {REPORT_GUIDE}).
:setvar LandingSchema landing
:setvar ReportSchema rpt
:setvar SiteUrl {setvar}
GO
"""


def _render_sql_view(plan: ListPlan) -> str:
    col_lines = [
        f"    CAST(t.[{name}] AS {sql_type}) AS [{name}]"
        for name, sql_type in plan.sql_columns
    ]
    col_lines.append(
        f"    CONCAT('$(SiteUrl){plan.item_url_path}', CAST(t.[Id] AS INT)) "
        "AS [ItemURL]",
    )
    cols = ",\n".join(col_lines)
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[vw_{plan.list_title}] AS\n"
        f"SELECT\n{cols}\n"
        f"FROM [$(LandingSchema)].[{plan.list_title}] AS t;\n"
        "GO\n"
    )


def _render_sql_enriched(plan: ListPlan) -> str:
    select_lines = ["    t.*"]
    join_lines = []
    for i, (fk_col, target_title, display, projections) in enumerate(
        plan.joins, start=1,
    ):
        alias = f"j{i}"
        base = fk_col.removesuffix("Id")
        select_lines.append(f"    {alias}.[{display}] AS [{base}{display}]")
        # The dependent lookups this column projects, off the SAME join the
        # display column already uses. Selected from the target's view rather
        # than from this list's landed table, because no extract is required
        # to have carried a read-only field across and the target's own view
        # has the column either way. `build_plans` has already dropped any
        # the target does not carry.
        select_lines += [
            f"    {alias}.[{target_column}] AS "
            f"[{projection_output_name(base, target_column)}]"
            for target_column in projections
        ]
        join_lines.append(
            f"LEFT JOIN [$(ReportSchema)].[vw_{target_title}] AS {alias}\n"
            f"    ON t.[{fk_col}] = {alias}.[Id]",
        )
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[vw_{plan.list_title}_Enriched] AS\n"
        "SELECT\n" + ",\n".join(select_lines) + "\n"
        f"FROM [$(ReportSchema)].[vw_{plan.list_title}] AS t\n"
        + "\n".join(join_lines) + ";\n"
        "GO\n"
    )


def generate_sql_views(
    schema: Schema, bundle: MappingBundle, site_role: str,
    *,
    site_url: str | None = None,
) -> str:
    """A single SQLCMD script: typed view per list + _Enriched join views.

    ``site_url``, when known, is written into the ``:setvar SiteUrl`` line
    so the script needs no editing; otherwise a placeholder is left there.
    """
    plans = build_plans(schema, bundle, site_role)
    parts = [_sql_header(site_url)]
    parts += [_render_sql_view(plan) for plan in plans]
    parts += [_render_sql_enriched(plan) for plan in plans if plan.joins]
    return "\n".join(parts)


# ------------------------------------------------------------ reporting guide


def _date_zone_guide_paragraphs(time_zone: str | None) -> list[str]:
    """What the guide says about `DateZoneResolved`, and about the declared
    zone's helpers where there is one."""
    if time_zone is None:
        return [
            (f"A list with a date-only column also carries "
             f"**{DATE_ZONE_RESOLVED_COLUMN}**, for the same reason. A "
             "date-only value is site-local midnight served as a UTC "
             "instant, so the query reads the site's time zone to turn it "
             "back into the date the list shows. That read fails soft too, "
             "and without it those columns truncate in UTC and read a day "
             "early east of UTC."),
        ]
    table = zone_table(time_zone)
    return [
        (f"Every list carries **{DATE_ZONE_RESOLVED_COLUMN}**, for the same "
         "reason. A date-only value is site-local midnight served as a UTC "
         "instant, so the query reads the site's time zone to turn it back "
         "into the date the list shows. That read fails soft too, and "
         "without it those columns truncate in UTC and read a day early "
         "east of UTC. The mapping declares the site's zone as "
         f"`{time_zone}`, so the flag is also false when the zone the site "
         "reports does not agree with it, which means the offsets the site "
         "reports are not exactly the ones that zone uses under its current "
         "rule: a pack built for one zone and refreshed against a site set "
         "to another says so on every row rather than converting timestamps "
         "by the wrong rule."),
        "",
        (f"Each list query also carries `{time_zone}`'s daylight-saving "
         f"transitions ({len(table.transitions)} rows, "
         f"{WINDOW_START:%Y-%m-%d} to {WINDOW_END:%Y-%m-%d}), generated from "
         "the IANA database when the pack was built, and two helpers over "
         "them: `AsSiteDateTime` turns a UTC timestamp such as `Created` "
         "into the site's local date and time, and `AsSiteDate` into its "
         "local date. Power Query has no time zone database of its own and "
         "SharePoint does not serve the transition dates, which is why they "
         "ship in the query. Regenerate the pack when the zone's rules "
         "change. A date-only column needs neither: its value is local "
         "midnight already, and the query resolves the offset from that."),
    ]


def _users_guide_paragraphs() -> list[str]:
    """What the guide says about `_Users` and the person keys, once."""
    return [
        (f"Person columns carry the site-user id (`...Id`), the display name "
         f"(`...Title`) and a `... Key` that joins **`{USERS_KEY_LIST}`** "
         "(`reporting.users_table` in the mapping): the site's user "
         "information list as one row per person, SharePoint group or "
         "domain group the site has ever resolved, with name, email, "
         "account, department, job title, office, a deleted flag and the "
         "principal kind. Department and job title come from the user "
         "profile and are blank until it has synced."),
        "",
        ("**Power BI allows one active relationship between two tables.** "
         "A list with several person columns therefore gets one active "
         f"relationship to `{USERS_KEY_LIST}` and the rest inactive. Either "
         "reach the inactive ones from measures with `USERELATIONSHIP`, or "
         f"reference `{USERS_KEY_LIST}` once per role (right-click, "
         "*Reference*, rename the copy to `Responsible User` and so on) and "
         "give each copy its own active relationship, which is what "
         "Microsoft recommends when a visual has to slice by more than one "
         "role at once."),
        "",
        ("Site user ids are per site collection, so `User Key` carries the "
         "site and the same person on two sites is two rows; the email is "
         "on the row for anyone who needs a cross-site people table. The "
         "list was read by a site admin when this was measured; a 403 on "
         "refresh means the reporting (reader) account needs read access "
         "to the site's user information list."),
    ]


def generate_reporting_md(
    schema: Schema, bundle: MappingBundle, site_role: str,
    *,
    site_url: str | None = None,
) -> str:
    """Usage instructions + the Power BI relationship table.

    ``site_url`` must be passed whenever the queries beside this guide were
    built with it: the setup step it documents is the difference between
    "create a parameter" and "there is nothing to create", and a guide that
    is wrong about that costs the operator the whole first hour.
    """
    plans = build_plans(schema, bundle, site_role)
    system_columns = bundle.mapping.reporting.system_columns
    users_table = bundle.mapping.reporting.users_table
    setup_step = (
        ("1. **Manage Parameters -> New parameter**: a *Text* parameter named "
         "`SiteUrl` holding the **site** URL, e.g. "
         "`https://tenant.sharepoint.com/sites/YourSite` (no trailing slash). "
         "That is the site, not a list or a page. Note the address bar shows the "
         "*list* URL (`.../Lists/YourList`) while you are looking at a list; "
         "each query trims that back to the site for you, so a pasted list, "
         "form, page or API URL still works.")
        if site_url is None else
        ("1. **Nothing to configure.** Each query already carries the site it "
         f"was built for (`{site_url}`) as its first line. See *Reporting on "
         "several sites at once* below to point a copy somewhere else.")
    )
    combine_steps = (
        [("1. Add one text parameter per site: `SiteUrl_North`, "
          "`SiteUrl_South`, and so on."),
         ("2. Duplicate each list query once per site (*right-click -> "
          "Duplicate*) and change `SiteUrl` in the duplicate to that site's "
          "parameter. Nothing else needs editing: the rows, the item links, "
          "the site name and the keys all follow that one reference.")]
        if site_url is None else
        [("1. Duplicate each list query once per site (*right-click -> "
          "Duplicate*)."),
         ("2. In each duplicate, change the one `SiteUrl = \"...\"` line to "
          "that site's URL, or replace it with a text parameter per site "
          "if you would rather manage them in one place. Nothing else needs "
          "editing: the rows, the item links, the site name and the keys "
          "all follow that one line.")]
    )
    lines = [
        "# Reporting queries",
        "",
        (f"Generated by dbml-sharepoint for site role `{site_role}` "
         f"(list prefix `{bundle.mapping.prefix}`). Regenerate with "
         "`dbml-sharepoint report` after any schema change. These queries "
         "stay in lockstep with the deployed lists only if they are "
         "regenerated together."),
        "",
        "## Power Query (M): Power BI Desktop / Excel",
        "",
        setup_step,
        ("2. For each `.pq` file: **Get Data -> Blank Query -> Advanced "
         "Editor**, paste the file contents, and rename the query to the "
         "list name (the first line of the file)."),
        ("3. When prompted to authenticate, choose **Organizational account** "
         "and sign in with an account that can read the lists."),
        "",
        ("Each query returns a typed table with lookup and person columns "
         "already expanded to a join key (`...Id`) plus a display column."),
        "",
        "## Reporting on several sites at once",
        "",
        ("This template is deployed one site at a time, but a report often "
         "needs all of them together: every region, service or committee "
         "running the same lists, in one model, sliced by site."),
        "",
        ("Every table already carries **`Site Url`**, **`Site Name`** and "
         "**`List Title`** for that, so a model that appends several "
         "deployments can slice by site and by list. The site name is read "
         "from the site's own title at refresh time, so nothing has to be "
         "typed in and a site renamed in SharePoint shows its new name at "
         "the next refresh."),
        "",
        ("Each query works that out for itself, from whichever URL it was "
         "given. That is deliberate: a single shared site-name query would "
         "bind to one `SiteUrl`, and every copy of a list pointed at a "
         "different site would still be stamped with the FIRST site's name."),
        "",
        "To combine deployments:",
        "",
        *combine_steps,
        ("3. **Append** the copies of a list into one table (*Home -> Append "
         "Queries as New*)."),
        ("4. Build the relationships below on the **Key** columns, not on "
         "`Id`."),
        "",
        (">  **`Id` is unique within one list on one site, and nowhere "
         "wider.** Append three sites and three different rows all have "
         "`Id = 1`, and so do the first rows of any two lists on a single "
         "site, because every list numbers its items from 1. A relationship "
         "on `Id` cannot then be many-to-one; Power BI degrades it to "
         "many-to-many and joins each child to the same-numbered parent "
         "everywhere. The report still renders. The numbers are just "
         "wrong. The `... Key` columns are `Site Url`, the **list title** and "
         "the id together, which is unique across any number of sites and "
         "lists, and they are why the relationships below are safe to "
         "append."),
        "",
        "## Relationships (Power BI model)",
        "",
        ("After loading the queries, create these many-to-one, "
         "single-direction relationships:"),
        "",
        "| From table | From column | To table | To column |",
        "|---|---|---|---|",
    ]
    for plan in plans:
        for fk_col, target_title, _display, _proj in plan.joins:
            target_entity = next(
                (p.entity for p in plans if p.list_title == target_title),
                target_title,
            )
            lines.append(
                f"| {plan.list_title} | {fk_key_column(fk_col)} "
                f"| {target_title} | {target_entity} Key |",
            )
        if plan.users_table:
            for name in plan.person_columns:
                lines.append(
                    f"| {plan.list_title} | {person_key_column(name)} "
                    f"| {USERS_KEY_LIST} | User{REPORT_KEY_SUFFIX} |",
                )
    lines += [
        "",
        *(_users_guide_paragraphs() if users_table else [
            ("Person columns carry the site-user id (`...Id`) and display "
             "name (`...Title`) but no relationship target. The site user "
             "list is not part of this schema."),
        ]),
        *(
            ["",
             ("Every list also carries SharePoint's **Created By**, "
              "**Created**, **Modified By** and **Modified** "
              "(`reporting.system_columns` in the mapping), after its own "
              "columns and in the same shape as a declared person or "
              "date-time column.")]
            if system_columns else []
        ),
        "",
        "## SQL views: warehouse landing zone",
        "",
        ("`sql/views.sql` assumes each list has been landed (by any extract "
         "process: Azure Data Factory, Power Automate, Dataflows) as a "
         "table named after the list, columns named after the SharePoint "
         "internal names, in the `$(LandingSchema)` schema. Lookup columns "
         "land as `...Id` integers; person columns land as display-name text. "
         + ("With `reporting.system_columns` on, each landed table must also "
            "carry `Author`, `Editor`, `Created` and `Modified`; a missing "
            "one fails the view by name rather than silently. "
            if system_columns else "")
         + "Run the script in SQLCMD mode after adjusting `:setvar "
         "LandingSchema` / `:setvar ReportSchema`."),
        "",
        ("**Multi-value choice columns are a landing contract, not a "
         "transform.** The Power Query queries join a set into one text cell "
         f'separated by `\"{MULTI_VALUE_JOIN}\"`, in a step written into the '
         "`.pq` file. The SQL views do not: they `CAST` whatever the extract "
         "landed, as `NVARCHAR(MAX)` so nothing is truncated in silence. "
         "Your extract must therefore land such a column as text, and the "
         "text it lands is the text your reports will read: SharePoint's "
         "own `;#`-delimited string, a JSON array, or the same "
         f'`\"{MULTI_VALUE_JOIN}\"` join, depending on the extractor. Match '
         "it to the Power Query separator if the two layers are to agree, or "
         "record which one your warehouse uses; this generator cannot see "
         "the extract and does not guess."),
        "",
        ("Per list you get `vw_<List>` (typed casts) and, where the list has "
         "lookups, `vw_<List>_Enriched` (lookups joined to their display "
         "columns), the horizontal, cross-list reporting layer."),
    ]
    lines += [
        "",
        ("Both layers add an **ItemURL** helper column (the SharePoint "
         "display-form link for the row), so any report visual can link "
         "straight back to the source item. The Power Query reads each "
         "list's own folder at refresh, so a list renamed in place still "
         "links correctly; the SQL views have no site to read and build the "
         "path from the declared title, which is a dead link for such a "
         "list. `data-dictionary.md` documents every list and column plus "
         "the deployment metadata behind this generation."),
        "",
        (f"The Power Query carries **{ITEM_URL_RESOLVED_COLUMN}** beside it, "
         "because that folder read fails soft: a permission that grants "
         "items but not the folder, a throttled call or a transient 503 all "
         "leave the refresh reporting success while every link in the table "
         "points at the declared title. Where the links matter, hide them on "
         f"the rows where {ITEM_URL_RESOLVED_COLUMN} is false rather than "
         "shipping a 404."),
        "",
        ("Where the mapping declares them, each query also carries "
         "**reporting-only columns**: flags, aggregates over a child list, "
         "and columns read from a related list, computed in the query and "
         "backed by no SharePoint field. `data-dictionary.md` marks each "
         "one, and the SQL views do not carry them."),
        "",
        ":::warning Load each query under the name of its file",
        ("A query that reads another list names it, so `GOV_Risk.pq` must "
         "be loaded as `GOV_Risk` for a query that reads it to resolve. "
         "Renaming a query breaks every derived column that reads it, at "
         "refresh. Appending several sites needs the same care: a "
         "duplicated query still reads the ORIGINAL copy of whatever it "
         "joins, so point each duplicate at its own copies. A count that "
         "finds itself reading another site's rows reports blank rather "
         "than zero, which is why the blank is worth checking."),
        ":::",
        "",
        *_date_zone_guide_paragraphs(bundle.mapping.reporting.time_zone),
        "",
        "## Data dictionary page (in-report)",
        "",
        ("The dictionary also ships as loadable data so every report can "
         "carry its own documentation page: load `_DataDictionary.pq` and "
         "`_ModelInfo.pq` alongside the list queries (they are static "
         "`#table` literals with no connection and no refresh cost), add a report "
         "page with a table visual over `_DataDictionary` sorted by "
         "`SortOrder`, and a card or table over `_ModelInfo` for the "
         "release/schema provenance. SQL consumers get the same rows as "
         f"`vw_{bundle.mapping.prefix}DataDictionary` and "
         f"`vw_{bundle.mapping.prefix}ModelInfo` (built from embedded "
         "VALUES, with no landing table needed)."),
    ]
    lines += [
        "",
        "## User-added column audit",
        "",
        ("Load `_UserAddedColumns.pq` alongside the dictionary queries. It "
         "reads each list's fields collection live on every refresh and "
         "returns the visible, deletable columns the schema does not "
         "declare. Expected EMPTY. Any row is a column added outside this "
         "generation: investigate it before trusting the model. "
         "Extension-expanded cross-site columns (if any) can appear; "
         "recognise them once. SQL consumers get "
         f"`vw_{bundle.mapping.prefix}UserAddedColumns` over "
         "INFORMATION_SCHEMA, which sees only columns the extract process "
         "lands, and extractor-added audit columns (e.g. `LoadDate`) "
         "appear there as recognisable rows."),
    ]
    skipped = [
        (plan.list_title, name) for plan in plans for name in plan.skipped
    ]
    if skipped:
        lines += [
            "",
            "## Columns not included",
            "",
            ("Cross-site reference columns are expanded at deploy time by the "
             "active extension into shapes this generator cannot know; add "
             "them to the queries by hand if needed:"),
            "",
        ]
        lines += [f"- {title}: `{name}`" for title, name in skipped]
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------- Data dictionary


def _md_cell(text: str) -> str:
    """Make free text safe inside a markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def _date_zone_dictionary_row(time_zone: str | None) -> str:
    """The helper-column row for `DateZoneResolved`, which means one thing
    more once the mapping declares the site's zone."""
    if time_zone is None:
        return (
            f"| {DATE_ZONE_RESOLVED_COLUMN} | Whether the site's time zone was "
            "read at refresh (only on lists that have a date-only column) "
            "| False means date-only columns were truncated in UTC and may be "
            "a day early east of UTC |"
        )
    return (
        f"| {DATE_ZONE_RESOLVED_COLUMN} | Whether the site's time zone was "
        f"read at refresh and agrees with the declared `{time_zone}` "
        "| False means date-only columns were truncated in UTC and may be a "
        "day early east of UTC, or the site is set to a zone other than the "
        "one the pack's timestamp conversions were built for |"
    )


def generate_data_dictionary(
    schema: Schema,
    bundle: MappingBundle,
    site_role: str,
    *,
    release: Release | None = None,
    generated_at: str = "",
    source_schema: str = "",
    source_mapping: str = "",
) -> str:
    """Companion data dictionary: deployment/schema metadata + every list and
    column as deployed, including choices, lookup targets, calculated
    formulas, indexing, versioning and the query-layer helper columns."""
    tables = tables_for_role(schema, bundle, site_role)
    enum_names = {e.name for e in schema.enums}
    enum_members = {e.name: e.members for e in schema.enums}
    cross_site_keys = bundle.mapping.cross_site_keys()
    mapping = bundle.mapping
    prefix = mapping.prefix
    # cross_site_keys above is exactly the pair set lookup_display_columns
    # needs, so the report excludes a cross-site ref's target for the same
    # reason the validator and the deployer do: it renders as a Choice + URL
    # pair, and no picker exists on the far side to protect.
    calculated_by_entity = {
        table.name: {c.name for c in table.columns if c.type in CALCULATED_TYPES}
        for table in schema.tables
    }
    display_columns = lookup_display_columns(
        schema, mapping.entities, calculated_by_entity, cross_site_keys,
    )

    lines = [
        f"# Data dictionary: `{prefix}` (site role `{site_role}`)",
        "",
        "## Deployment / schema model metadata",
        "",
        "| Field | Value |",
        "|---|---|",
    ]
    lines += [
        f"| {field_name} | {_md_cell(value)} |"
        for field_name, value in metadata_rows(
            bundle, site_role, len(tables),
            release, generated_at, source_schema, source_mapping,
        )
    ]

    for table in tables:
        entity = mapping.entities[table.name]
        list_title = prefix + table.name
        heading = (
            f"## {list_title}: entity `{table.name}` "
            f"({entity.kind}, template {entity.base_template}"
            + (", singleton" if entity.singleton else "")
            + ")"
        )
        lines += ["", heading, ""]
        if table.note:
            lines += [_md_cell(table.note), ""]
        lines += [
            ("| Column | SharePoint type | Required | Unique | Default | "
             "Retired | Superseded by | Populated when | Save rule | Description |"),
            "|---|---|---|---|---|---|---|---|---|---|",
        ]
        for (
            name, type_cell, required, unique, default,
            retired, superseded_by, populated, rule, description,
        ) in column_rows_for_table(
            table, bundle, enum_names, enum_members, cross_site_keys,
        ):
            lines.append(
                f"| {name} | {_md_cell(type_cell)} | {required} | {unique} | "
                f"{_md_cell(default)} | {retired} | {superseded_by} | "
                f"{_md_cell(populated)} | {_md_cell(rule)} | "
                f"{_md_cell(description)} |",
            )
        details: list[str] = []
        # The declared indexes PLUS the one a lookup target gets for free. A
        # list that anything looks up is indexed on its display column so the
        # picker keeps working past 5,000 items, and that index spends one of
        # the twenty, so a dictionary listing only the declared ones
        # understates a budget an author is reading this page to manage.
        # Derived from the same lookup_display_columns the deployer emits from,
        # so the report cannot disagree with what is deployed.
        indexed = list(deployable_index_columns(table))
        display = display_columns.get(table.name)
        if display is not None and display not in indexed:
            indexed.append(f"{display} (lookup display column)")
        if indexed:
            details.append(f"Indexed columns: {', '.join(indexed)}.")
        # `versioning_for` rather than the merge again: this page tells a
        # reader what the list was provisioned with, so it has to be the same
        # answer jsgen sent.
        versioning = mapping.versioning_for(table.name)
        if versioning.enable_versioning:
            details.append(
                "Versioning: major versions on, limit "
                f"{versioning.major_version_limit}"
                + (", minor versions on" if versioning.enable_minor_versions else "")
                + ".",
            )
        else:
            details.append("Versioning: off.")
        lines += ["", " ".join(details)]

    if mapping.reporting.users_table:
        lines += [
            "",
            f"## {USERS_KEY_LIST}: the site's user information list",
            "",
            ("Not a list of this schema. One row per person, SharePoint group "
             "or domain group the site has ever resolved, read from "
             "`/_api/web/siteuserinfolist`, carrying `Site Url` and "
             "`Site Name` like every list table. Every person column's "
             "`... Key` joins `User Key` here; guide.md has the relationships "
             "and the one-active rule."),
            "",
            "| Column | SharePoint type | Description |",
            "|---|---|---|",
            *(
                f"| {name} | {_md_cell(type_cell)} | {_md_cell(description)} |"
                for name, type_cell, _r, _u, _d, _re, _s, _p, _ru, description
                in users_dictionary_rows()
            ),
        ]
    lines += [
        "",
        "## Helper columns (query layer only)",
        "",
        ("Added by every generated Power Query and SQL view; they are "
         "constructed at query time and do not exist on the lists:"),
        "",
        "| Column | Construction | Purpose |",
        "|---|---|---|",
        ("| ItemURL | The list's own folder, read at refresh, + item id "
         "(the SQL views use the declared list path instead) | Direct link "
         "from any report row back to the SharePoint item (display form) |"),
        (f"| {ITEM_URL_RESOLVED_COLUMN} | Whether that folder read succeeded "
         "| False means every ItemURL in the table was built from the "
         "declared title, which is a dead link on a list that has been "
         "renamed. Suppress the link rather than ship a 404 |"),
        _date_zone_dictionary_row(mapping.reporting.time_zone),
        ("| ...Id / ...Title (lookups, person) | `$select`/`$expand` of the "
         "lookup | Join key plus display column without a second query |"),
        "",
        "## Reporting-only columns",
        "",
        ("Columns marked **Reporting only** above are computed in the "
         "generated Power Query and exist nowhere else. No SharePoint field "
         "stands behind one, no list carries it, and a site search will not "
         "find it. They are declared in the mapping beside the schema, so "
         "the report and the lists are generated from one description "
         "rather than two."),
        "",
        ("They are Power Query only. The SQL views carry the lists' own "
         "columns and the lookup joins, and none of these, because a "
         "row-level expression written in M has no SQL to translate to."),
        "",
        "## Blank in a column marked required",
        "",
        ("A column's Required cell says what SharePoint enforces on SAVE, "
         "which is not the same as what every row holds. SharePoint applies "
         "a column default to NEW items only, so a required column with a "
         "default reads blank on every row created before that column was "
         "added to the list, and stays blank until somebody edits the row "
         "or bulk-edits the column. The generated queries pass those blanks "
         "through unchanged."),
        "",
        ("A blank in such a column therefore means either that the row "
         "predates the column or that somebody cleared it, and nothing in "
         "the feed separates the two. Where that distinction matters, "
         "compare the row's Created against the release that added the "
         "column rather than reading the blank as a data quality problem."),
        "",
    ]
    return "\n".join(lines)


# ----------------------------------------- Dictionary as report-loadable data


def _sql_string(text: str) -> str:
    """An N'...' T-SQL literal: single quotes are escaped by doubling."""
    return "N'" + text.replace("'", "''") + "'"


def _render_sql_values_view(
    view_name: str, columns: list[str], row_literals: list[str],
) -> str:
    col_list = ", ".join(f"[{c}]" for c in columns)
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[{view_name}] AS\n"
        f"SELECT {col_list}\n"
        "FROM (VALUES\n"
        + ",\n".join(f"    ({row})" for row in row_literals)
        + f"\n) AS v({col_list});\n"
        "GO\n"
    )


def _render_user_added_columns_sql(plans: list[ListPlan], prefix: str) -> str:
    """Drift-audit view over the landing schema: columns present on the
    landed tables that the schema does not declare. Sees only what the
    extract process lands (the M audit query is the live control);
    extractor-added audit columns (e.g. LoadDate) surface as recognisable
    rows."""
    if not plans:
        return ""
    table_list = ", ".join(_sql_string(plan.list_title) for plan in plans)
    expected_rows = []
    for plan in plans:
        names = ["Id"] + [name for name, _ in plan.sql_columns]
        for name in dict.fromkeys(names):
            expected_rows.append(
                f"    ({_sql_string(plan.list_title)}, {_sql_string(name)})",
            )
    # Emitting SQL text is this generator's purpose; identifiers come
    # from the validated schema, never from runtime user input.
    return (
        f"CREATE OR ALTER VIEW [$(ReportSchema)].[vw_{prefix}UserAddedColumns] AS\n"  # noqa: S608
        "-- Drift audit: landed columns the schema does not declare. Expected\n"
        "-- EMPTY. Only sees columns the extract process lands.\n"
        "SELECT c.TABLE_NAME AS [List], c.COLUMN_NAME AS [Column],\n"
        "       c.DATA_TYPE AS [LandedType]\n"
        "FROM INFORMATION_SCHEMA.COLUMNS AS c\n"
        "WHERE c.TABLE_SCHEMA = '$(LandingSchema)'\n"
        f"  AND c.TABLE_NAME IN ({table_list})\n"
        "  AND NOT EXISTS (SELECT 1 FROM (VALUES\n"
        + ",\n".join(expected_rows)
        + "\n  ) AS d([List], [Column])\n"
        "  WHERE d.[List] = c.TABLE_NAME AND d.[Column] = c.COLUMN_NAME);\n"
        "GO\n"
    )


def generate_dictionary_sql(
    schema: Schema,
    bundle: MappingBundle,
    site_role: str,
    *,
    release: Release | None = None,
    generated_at: str = "",
    source_schema: str = "",
    source_mapping: str = "",
) -> str:
    """The data dictionary as SQL views built from embedded VALUES rows (no
    landing table needed), so warehouse-driven reports can surface the same
    dictionary page."""
    prefix = bundle.mapping.prefix
    dd_rows = [
        ", ".join([str(i)] + [_sql_string(cell) for cell in row])
        for i, row in enumerate(dictionary_rows(schema, bundle, site_role), start=1)
    ]
    tables = tables_for_role(schema, bundle, site_role)
    mi_rows = [
        _sql_string(field_name) + ", " + _sql_string(value)
        for field_name, value in metadata_rows(
            bundle, site_role, len(tables),
            release, generated_at, source_schema, source_mapping,
        )
    ]
    audit_view = _render_user_added_columns_sql(
        build_plans(schema, bundle, site_role), prefix,
    )
    return (
        _render_sql_values_view(
            f"vw_{prefix}DataDictionary",
            ["SortOrder", "List", "Column", "Type",
             "Required", "Unique", "Default", "Retired", "SupersededBy",
             "PopulatedWhen", "SaveRule", "Description"],
            dd_rows,
        )
        + "\n"
        + _render_sql_values_view(
            f"vw_{prefix}ModelInfo", ["Field", "Value"], mi_rows,
        )
        + ("\n" + audit_view if audit_view else "")
    )


def emit_reporting(
    out: Path,
    schema: Schema,
    bundle: MappingBundle,
    site_role: str,
    *,
    release: Release | None,
    generated_at: str,
    source_schema: str,
    source_mapping: str,
    site_url: str | None = None,
) -> list[str]:
    """Write the reporting bundle under ``out/reporting/`` and return the
    POSIX relpaths written (for checksums.txt).

    Shared by the core and extension CLIs so the shipped reporting
    artifact set cannot drift between them: per-list Power Query (M)
    plus the dictionary/model/audit queries, the SQL views script,
    the reporting guide and the data dictionary.

    ``site_url`` is the deployment target, which ``build`` always has.
    Passing it bakes the site into every query, the SQL script and the
    guide, so the pack loads with nothing configured. It is optional only
    because ``report`` runs without a site at all.
    """
    reporting_dir = out / REPORT_DIR
    pq_dir = reporting_dir / "powerquery"
    sql_dir = reporting_dir / "sql"
    pq_dir.mkdir(parents=True, exist_ok=True)
    sql_dir.mkdir(parents=True, exist_ok=True)
    dictionary_kwargs: dict[str, Any] = dict(
        release=release,
        generated_at=generated_at,
        source_schema=source_schema,
        source_mapping=source_mapping,
    )
    relpaths: list[str] = []
    queries = generate_powerquery(schema, bundle, site_role, site_url=site_url)
    queries.update(
        generate_dictionary_powerquery(
            schema, bundle, site_role, site_url=site_url, **dictionary_kwargs,
        ),
    )
    for filename, content in queries.items():
        write_artifact(pq_dir / filename, content)
        relpaths.append(f"reporting/powerquery/{filename}")
    write_artifact(
        sql_dir / REPORT_VIEWS_SQL,
        generate_sql_views(schema, bundle, site_role, site_url=site_url)
        + "\n"
        + generate_dictionary_sql(schema, bundle, site_role, **dictionary_kwargs),
    )
    write_artifact(
        reporting_dir / REPORT_GUIDE,
        generate_reporting_md(schema, bundle, site_role, site_url=site_url),
    )
    write_artifact(
        reporting_dir / REPORT_DICTIONARY,
        generate_data_dictionary(schema, bundle, site_role, **dictionary_kwargs),
    )
    relpaths += [
        f"{REPORT_DIR}/sql/{REPORT_VIEWS_SQL}",
        f"{REPORT_DIR}/{REPORT_GUIDE}",
        f"{REPORT_DIR}/{REPORT_DICTIONARY}",
    ]
    return relpaths
